name: Tailwind Component Feature Template
description: File a Feature issue report
title: "[TCF]: "
body:
  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      placeholder: ex. FEATURE Title
    validations:
      required: true
  - type: textarea
    id: Description
    attributes:
      label: Description
      placeholder: Description of the TAILWIND COMPONENT FEATURE
    validations:
      required: true
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot of the tailwind component
    validations:
      required: false
  - type: input
    id: implementaion
    attributes:
      label: Are you taking this fetaure implementaion
      placeholder: Yes/ No
    validations:
      required: true